## Consulta grupos ativos

In [1]:
import os
import pandas as pd
import psycopg2

# Definir os parâmetros de conexão com o PostgreSQL
usuario = 'postgres'
senha = '87a9f05e0b51d376b83d582111c280da'
host = '147.79.110.26'  # Endereço do servidor do banco
porta = '5432'           # Porta padrão do PostgreSQL
banco_de_dados = 'botai_dev'

# Definir diretórios
dir_chat_hist = 'Dados/ChatHistory'

In [6]:
try:
    # Estabelecendo conexão com o banco de dados
    conn = psycopg2.connect(
        dbname=banco_de_dados,
        user=usuario,
        password=senha,
        host=host,
        port=porta
    )
    
    # Query para selecionar todos os dados da tabela desejada
    query = f"SELECT * FROM groups WHERE status = 'ativo';"
    
    # Lendo os dados diretamente no DataFrame
    grupos_ativos = pd.read_sql_query(query, conn)
    
    # Fechando a conexão
    conn.close()
    
except Exception as e:
    print(f"Erro ao conectar ao banco de dados: {e}")

/tmp/ipykernel_630998/3496927855.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  grupos_ativos = pd.read_sql_query(query, conn)

In [7]:
grupos_ativos

,group_id,group_jid,group_name,package_id,project_id,status,description,created_at,updated_at
0,2,024509451509359969@g.us,Maiara-Mayavant,2,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
1,3,025587043275878954@g.us,EduardoeNicolas-MulherdaWeb,1,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
2,4,171622593129764632@g.us,Plinio-Vibefortech,2,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
3,5,176569235456585413@g.us,SamueleLeonardo-Linqtec,1,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
4,6,220191283813053475@g.us,Dr.MuriloeMurilo-Dynathlete,2,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
5,7,319892153194284268@g.us,Pedro-StoreForKids,1,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
6,8,370613401684902859@g.us,MarianaeRita-ExpressodoAconchego,1,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
7,9,436283272096070764@g.us,TâniaeThaissa-TajuvanHouse,1,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
8,10,765321137722616028@g.us,Nitiel-Apertto,2,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
9,11,960751260776592837@g.us,Tiago-AkkiShop,2,2,ativo,None,2024-10-04 02:25:11.187973,2024-10-04 02:25:11.187973
10,12,120363326967634240@g.us,Nome do projeto,1,12,ativo,Descrição do grupo,2024-10-04 12:48:25.160881,2024-10-04 12:48:25.160884